name: Vue Build Check # 工作流名称

on: [push] # 触发时机：每次 push 代码时

jobs:
    build:
        runs-on: ubuntu-latest # 在 Linux 环境运行

        steps:
            - uses: actions/checkout@v4 # 第一步：把 Git 代码拉取到云端服务器

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20" # 设置 Node 环境

            - name: Install Dependencies
              run: npm install # 安装依赖

            - name: Build Project
              run: npm run build # 尝试打包
